version: "2.1"
networks:
  internal_network:
services:      
  db:
#    image: repo.ambar.cloud:443/ambar-mongodb:2.1
    image: mlucasdasilva/ambar-mongodb:2.1
    restart: always
    build:
      context: ./MongoDB
    environment:
      - cacheSizeGB=2
    volumes:
      - db-data:/data/db
    expose:
      - "27017"   
    networks:
      - internal_network
  es:
#    image: repo.ambar.cloud:443/ambar-es:2.1
    image: mlucasdasilva/ambar-es:2.1
    restart: always
    build:
      context: ./ElasticSearch
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200" 
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - internal_network
  kibana:
#    image: kibana:5.6.3
    image: mlucasdasilva/ambar-kibana:2.1
    restart: always
    build:
      context: ./Kibana
    ports:
      - "5601:5601"
    depends_on:
      es:
        condition: service_healthy
    links:
      - es:elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 30s
      retries: 50
    networks:
      - internal_network
  rabbit:
#    image: repo.ambar.cloud:443/ambar-rabbit:2.1
    image: mlucasdasilva/ambar-rabbit:2.1
    restart: always
    build:
      context: ./Rabbit
    hostname: rabbit
    expose:
      - "15672"
      - "5672"   
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    networks:
      - internal_network
  redis:
#    image: repo.ambar.cloud:443/ambar-redis:2.1
    image: mlucasdasilva/ambar-redis:2.1
    restart: always
    build:
      context: ./Redis
    expose:
      - "6379" 
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal_network
  serviceapi:
#    image: repo.ambar.cloud:443/ambar-serviceapi:2.1
    image: mlucasdasilva/ambar-serviceapi:2.1
    restart: always
    build:
      context: ./ServiceApi
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=${langAnalyzer}  
      - SLAO_HOSTNAME=ambar 
      - SLAO_API_KEY=
    expose:
      - "8081"  
    networks:
      - internal_network
  webapi:
#    image: repo.ambar.cloud:443/ambar-webapi:2.1
    image: mlucasdasilva/ambar-webapi:2.1
    restart: always
    build:
      context: ./WebApi
    depends_on:
      serviceapi:
        condition: service_healthy
    environment:            
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit  
      - SLAO_HOSTNAME=ambar
      - SLAO_API_KEY=  
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - internal_network
  frontend:
#    image: repo.ambar.cloud:443/ambar-frontend:2.1
    image: mlucasdasilva/ambar-frontend:2.1
    restart: always
    build:
      context: ./FrontEnd
    depends_on:
      webapi:
        condition: service_healthy
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - api=http://${ambarHostIpAddress}:8080  
    networks:
      - internal_network
  pipeline0:
#    image: repo.ambar.cloud:443/ambar-pipeline:2.1
    image: mlucasdasilva/ambar-pipeline:2.1
    restart: always
    build:
      context: ./Pipeline
    depends_on: 
      serviceapi: 
        condition: service_healthy                            
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
    networks:
      - internal_network  
  my-crawler:
#    image: repo.ambar.cloud:443/ambar-local-crawler:2.1
    image: mlucasdasilva/ambar-local-crawler:2.1
    restart: always
    build:
      context: ./LocalCrawler
    depends_on: 
      serviceapi: 
        condition: service_healthy 
      pipeline0:
        condition: service_healthy
    expose:
      - "8082"
    environment:      
      - name=my-crawler
      - ignoreFolders=**/ForSharing/**
      - ignoreExtensions=.{exe,dll,rar}
      - ignoreFileNames=*backup*
      - maxFileSize=15mb
    volumes:
      - ${pathToCrawl}:/usr/data
    networks:
      - internal_network

volumes:
   db-data:
   es-data:
   rabbit-data:
  
