version: "2.1"
networks:
  internal_network:
services:      
  db:
    restart: always
    networks:
      - internal_network
#    image: repo.ambar.cloud:443/ambar-mongodb:2.1
    image: mlucasdasilva/ambar-mongodb:2.1
    build:
      context: ./MongoDB
    environment:
      - cacheSizeGB=2
    volumes:
      - db-data:/data/db
    expose:
      - "27017"   
  es:
    restart: always
    networks:
      - internal_network
#    image: repo.ambar.cloud:443/ambar-es:2.1
    image: mlucasdasilva/ambar-es:2.1
    build:
      context: ./ElasticSearch
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200" 
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana:
    networks:
      - internal_network
#    image: kibana:5.6.3
    image: mlucasdasilva/ambar-kibana:2.1
    build:
      context: ./Kibana
    ports:
      - "5601:5601"
    depends_on:
      es:
        condition: service_healthy
    links:
      - es:elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 30s
      retries: 50
  rabbit:
    restart: always
    networks:
      - internal_network
#    image: repo.ambar.cloud:443/ambar-rabbit:2.1
    image: mlucasdasilva/ambar-rabbit:2.1
    build:
      context: ./Rabbit
    hostname: rabbit
    expose:
      - "15672"
      - "5672"   
    volumes:
      - rabbit-data:/var/lib/rabbitmq
  redis:
    networks:
      - internal_network
    restart: always
    sysctls:
      - net.core.somaxconn=1024
#    image: repo.ambar.cloud:443/ambar-redis:2.1
    image: mlucasdasilva/ambar-redis:2.1
    build:
      context: ./Redis
    expose:
      - "6379" 
  serviceapi:
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
#    image: repo.ambar.cloud:443/ambar-serviceapi:2.1
    image: mlucasdasilva/ambar-serviceapi:2.1
    build:
      context: ./ServiceApi
    expose:
      - "8081"  
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=${langAnalyzer}  
      - SLAO_HOSTNAME=ambar 
      - SLAO_API_KEY=
  webapi:
    depends_on:
      serviceapi:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
#    image: repo.ambar.cloud:443/ambar-webapi:2.1
    image: mlucasdasilva/ambar-webapi:2.1
    build:
      context: ./WebApi
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:            
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit  
      - SLAO_HOSTNAME=ambar
      - SLAO_API_KEY=  
  frontend:
    depends_on:
      webapi:
        condition: service_healthy
#    image: repo.ambar.cloud:443/ambar-frontend:2.1
    image: mlucasdasilva/ambar-frontend:2.1
    build:
      context: ./FrontEnd
    restart: always
    networks:
      - internal_network
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - api=http://${ambarHostIpAddress}:8080  
  pipeline0:
    depends_on: 
      serviceapi: 
        condition: service_healthy                            
#    image: repo.ambar.cloud:443/ambar-pipeline:2.1
    image: mlucasdasilva/ambar-pipeline:2.1
    build:
      context: ./Pipeline
    restart: always
    networks:
      - internal_network  
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
  crawler1:
    depends_on: 
      serviceapi: 
        condition: service_healthy 
#    image: repo.ambar.cloud:443/ambar-local-crawler:2.1
    image: mlucasdasilva/ambar-local-crawler:2.1
    build:
      context: ./LocalCrawler
    restart: always
    networks:
      - internal_network
    expose:
      - "8082"
    environment:      
      - name=crawler1
    volumes:
      - ${pathToCrawl}:/usr/data

volumes:
   db-data:
   es-data:
   rabbit-data:
  
